### PR TITLE
replace np.bool with bool

### PR DESCRIPTION
**Pull request by RebeccaColquhoun**
Fixes issue #5 

np.bool is depreciated, and was just an alias for the built in bool. Replaced np.bool with bool.

### CODE REVIEW

**Comment by alvarosg** [comment]
Thanks!

**Comment by matiasg** [comment]
@alvarosg Would you please do a PyPI release with this PR merged?

**Comment by alvarosg** [comment]
Hi! So after your PR I decided to deprecate installation from PyPi, and instead encourage users to install from github directly. And also updated the instructions to do to in the main README.

Would that work for you?

Note you can specify also this in the installation requirements (e.g. https://stackoverflow.com/a/35998253).

Hope this helps!

**Comment by matiasg** [comment]
Yes, it works. Thanks for the clarification.

Actually, the PR is not mine. I was about to report the same problem but saw that it had been already solved.

**Comment by RGD2** [comment]
Hi! 
I just came here now to find the issue I was about to report, had been fixed two weeks ago!

( serious mode: off)
For everyone else here, here's a fix you can do with the sadly unmaintained pypi version you had which brought you here:

Step 1: Copy inverse.py into your working directory, you can use the path the error message gives you.
Step 2: `!sed -i 's/np.bool/bool/' inverse.py`
Step 3: Change `from pynverse import inversefunc` to `from inverse import inversefunc`

Oh, wait, never mind all that - you should simply have known to install pynverse from the git repo, not from pypi (because it's super special and deserves extra special treatment). Don't worry! you can just have a special line in your requirements.txt so apart from needing to know that you have to install it this way.
(serious mode: on)

In all honesty, I am very glad to see that this excellent project is still so freshly maintained. It's always a bit of a blow to the guts when  you do a fresh install and find old code breaking due to little cleanups like this, not because it's a big problem, more because it could indicate that the maintainers have lost interest.

I just so had a need pop up for it (linearizing a sensor), and it was as perfect as I recall. I did have a little trouble remembering what to `pip install`, but a google for pypi pyinverse found it, (although google did a 'did you mean pyreverse?' first, and also annoyingly, searching directly on pypi.python.org for pyinverse actually still gets a 'did you mean pyniverse?' and doesn't find it at all. (seriously, are the search engines trying to suppress you??)

I think you should just rename this `pyinverse` and put it on pypi. 

Which is where I originally stumbled across it, whilst looking for other things.  

Noone else on pypi has 'pyinverse', and as that's the name I dimmly recalled it to be, it's probably not a terribly bad choice in the first place, at least not from my perspective as a forgetful occasional user. 

As an experimental scientist, it gets my vote. A great example of a genuinely useful library to do something difficult with practicality. A devastating combo with scipy for curve fitting for interpolation from calibration data.

Choosing to just not be updated on pypi means you'll see and help fewer new people. Your surface for discovery goes way down. (although, even at the moment, the name being a common mispelling for inverse seems to be doing that anyway, sadly enough. I mean, seriously: pypi search for pyinverse finds 'pyniverse' but NOT 'pynverse' ??).

Anyway, thanks for the great work, I'd better get back to my own.

Cheers!

**Comment by alvarosg** [comment]
I have updated the PyPI version as a one-off to save existing users some trouble. Name is staying as it is though :)

**Pull request merged**
